### ISSUE TITLE
Type mismatch on Linux i686

### ISSUE THREAD

**Issue by smartmic** [Tormund/file_dialog#4]
I got the following error when compiling the sample code:
```
/home/martin/.nimble/pkgs/os_files-0.1.1/os_files/private_dialog/unix_dialog.nim(57, 
16) Error: type mismatch: got <nil> but expected 'string'
```
Solution: Changing *nil* to an empty string *""* in the assignment of `result` in line 57 solved the problem for me ↦ `        result = ""`

**Comment by Tormund** [comment]
Can you provide PR with fix?
